/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: 'Open directory',
  key0002: 'Front-end management system',
  key0003: 'Backend service closed successfully',
  key0004: 'Shutdown system',
  key0005: 'Project',
  key0006: 'Service',
  key0007: '{v1} command has been sent',
  key0008: 'Not open',
  key0009: 'Closed',
  key0010: 'Error',
  key0011: 'Compiling..',
  key0012: 'Success',
  key0013: 'Unknown',
  key0014: 'Start service',
  key0015: 'Stop service',
  key0016: 'Restart service',
  key0017: 'View log',
  key0018: 'Clear log',
  key0019: 'Service management',
  key0020: 'Description',
  key0021: 'Command',
  key0022: 'Port',
  key0023: 'Address',
  key0024: 'Operation',
  key0025: 'Delete service',
  key0026: 'Delete service?',
  key0027: 'Deleted successfully',
  key0028: 'Edit service',
  key0029: 'Project management',
  key0030: 'Add project',
  key0031: 'Add processes to the project',
  key0032: 'Edit project',
  key0033: 'Delete project',
  key0034: 'Do you want to delete the project?',
  key0035: 'Also delete the owned services',
  key0036: 'Create a new project',
  key0037: 'Operation successful',
  key0038: 'Folder address',
  key0039: 'Folder address cannot be empty',
  key0040: 'Name or description',
  key0041: 'Create a new service',
  key0042: 'Command cannot be empty',
  key0043: 'Port cannot be empty',
};

export default locale;
