logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:file:./h2db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    serialization:
      write-date-timestamps-as-nanoseconds: false
      write-dates-as-timestamps: true


